//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAngularEntity.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidato()
        {
            this.CandidatoBuscaVagas = new HashSet<CandidatoBuscaVaga>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Skype { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Linkedin { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> PretencaoSalario { get; set; }
        public Nullable<decimal> PretencaoSalarioHora { get; set; }
        public Nullable<int> NivelCSharp { get; set; }
        public Nullable<int> NivelAspNetMvc { get; set; }
        public Nullable<int> NivelAngularJs { get; set; }
        public Nullable<int> NivelJquery { get; set; }
        public Nullable<int> NivelBootstrap { get; set; }
        public Nullable<int> NivelWordpress { get; set; }
        public Nullable<int> NivelPhp { get; set; }
        public Nullable<int> NivelAndroid { get; set; }
        public Nullable<int> NidelIos { get; set; }
        public Nullable<int> NivelIonic { get; set; }
        public string Portifolio { get; set; }
        public string ConhecimentoLinguagens { get; set; }
        public string ConhecimentoSGC { get; set; }
        public string AreaInteresse { get; set; }
        public Nullable<int> HorasDisponivel { get; set; }
        public string HorarioDisponivel { get; set; }
        public Nullable<int> BuscaTipoVaga { get; set; }
        public string InformacaoBancaria { get; set; }
        public string ComentarioAdicional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatoBuscaVaga> CandidatoBuscaVagas { get; set; }
    }
}
